use_frameworks!

platform :ios, '9.0'

target 'JWBaseLib_Example' do
  pod 'JWBaseLib', :path => '../'

  target 'JWBaseLib_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
